task_type:                    sin           # which task to meta-learn e.g. sin- for sinusoid regression
training_iterations:          250000        # number of training iterations (total calls to the outer training loop)
task_batch_size:              25            # number of tasks sampled per meta-update (per outer loop)
meta_lr:                      0.001         # the base learning rate of the generator (the outer loop optimiser)
inner_update_batch_size:      10            # number of examples used for inner gradient update (k for k-shot learning)
inner_update_lr:              0.001         # step size alpha for inner gradient update
num_inner_updates:            1             # number of inner gradient updates during training
validation_task_batch_size:   10            # number of tasks to sample and evaluate in each validation loop
validation_frequency:         200           # frequency with which to perform validation during training
x_dim:                        1             # dimension of x input 

resume:                       /data/home/tsel/maml/results/2019-07-21-15-56-53/model_checkpoint_18-18-02.pt